name: Build Multi-Platform Executable

on:
  push:
    branches: [ main, master ]
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: quick-vjs-windows-x64.exe
            compile_cmd: bun build ./src/index.ts --compile --minify --bytecode --outfile quick-vjs-windows-x64.exe
          - os: macos-latest
            artifact_name: quick-vjs-macos-arm64
            compile_cmd: bun build ./src/index.ts --compile --minify --bytecode --outfile quick-vjs-macos-arm64
          - os: macos-13
            artifact_name: quick-vjs-macos-x64
            compile_cmd: bun build ./src/index.ts --compile --minify --bytecode --outfile quick-vjs-macos-x64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Compile Executable Native
        run: ${{ matrix.compile_cmd }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ./${{ matrix.artifact_name }}
